# Generated by Django 5.1.2 on 2024-11-05 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(verbose_name='telegram id')),
                ('telegram_username', models.CharField(verbose_name='telegram username')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='о себе')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='img/profile_images/%Y-%d-%m/', verbose_name='изображение профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'аккаунт',
                'verbose_name_plural': 'аккаунты',
            },
        ),
    ]
