# Generated by Django 5.1.2 on 2024-11-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('description', models.TextField(verbose_name='описание')),
                ('date', models.DateTimeField(verbose_name='дата и время')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('number_of_members', models.PositiveIntegerField(verbose_name='количество участников')),
                ('is_open', models.BooleanField(verbose_name='открыта')),
            ],
            options={
                'verbose_name': 'встреча',
                'verbose_name_plural': 'встречи',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='accounts.account', verbose_name='аккаунт')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='meets.meet', verbose_name='аккаунт')),
            ],
            options={
                'verbose_name': 'участник',
                'verbose_name_plural': 'участники',
                'constraints': [models.UniqueConstraint(fields=('account', 'meet'), name='unique_participation')],
            },
        ),
    ]
